// <auto-generated />
using System;
using API.SIGE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.SIGE.Migrations
{
    [DbContext(typeof(AppDbData))]
    [Migration("20260402225316_FixSenhaColumnLength")]
    partial class FixSenhaColumnLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.SIGE.Models.Anexo", b =>
                {
                    b.Property<int>("IdAnexo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnexo"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("Dados")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdMedicao")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProducaoFamilia")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoAnexo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoArquivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdAnexo");

                    b.HasIndex("IdMedicao");

                    b.HasIndex("IdProducaoFamilia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Anexo");
                });

            modelBuilder.Entity("API.SIGE.Models.Caixilho", b =>
                {
                    b.Property<int>("IdCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCaixilho"));

                    b.Property<int>("Altura")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataLiberacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoCaixilho")
                        .HasColumnType("text");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("Largura")
                        .HasColumnType("integer");

                    b.Property<bool>("Liberado")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCaixilho")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ObraId")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("PesoUnitario")
                        .HasColumnType("real");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("StatusProducao")
                        .HasColumnType("integer");

                    b.HasKey("IdCaixilho");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("ObraId");

                    b.ToTable("Caixilho");
                });

            modelBuilder.Entity("API.SIGE.Models.Cargo", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCargo"));

                    b.Property<string>("DescricaoCargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoCargo")
                        .HasColumnType("integer");

                    b.HasKey("IdCargo");

                    b.HasIndex("TipoCargo")
                        .IsUnique();

                    b.ToTable("Cargo");

                    b.HasData(
                        new
                        {
                            IdCargo = 1,
                            DescricaoCargo = "Gerente",
                            TipoCargo = 1
                        },
                        new
                        {
                            IdCargo = 2,
                            DescricaoCargo = "Responsável pela Verificação",
                            TipoCargo = 2
                        },
                        new
                        {
                            IdCargo = 3,
                            DescricaoCargo = "Responsável pela Medição",
                            TipoCargo = 3
                        },
                        new
                        {
                            IdCargo = 4,
                            DescricaoCargo = "Responsável pela Produção",
                            TipoCargo = 4
                        });
                });

            modelBuilder.Entity("API.SIGE.Models.FamiliaCaixilho", b =>
                {
                    b.Property<int>("IdFamiliaCaixilho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFamiliaCaixilho"));

                    b.Property<string>("DescricaoFamilia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdObra")
                        .HasColumnType("integer");

                    b.Property<int>("PesoTotal")
                        .HasColumnType("integer");

                    b.Property<int>("StatusFamilia")
                        .HasColumnType("integer");

                    b.HasKey("IdFamiliaCaixilho");

                    b.HasIndex("IdObra");

                    b.ToTable("FamiliaCaixilho");
                });

            modelBuilder.Entity("API.SIGE.Models.Medicao", b =>
                {
                    b.Property<int>("IdMedicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMedicao"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEstimadaConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IdMedicao");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("Medicao");
                });

            modelBuilder.Entity("API.SIGE.Models.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNotificacao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdObra")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioDestino")
                        .HasColumnType("integer");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("TipoNotificacao")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdUsuarioDestino");

                    b.ToTable("Notificacao");
                });

            modelBuilder.Entity("API.SIGE.Models.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdObra"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Construtora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataTermino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdResponsavelMedicao")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResponsavelProducao")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResponsavelVerificacao")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("ImagemObraPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("PercentualConclusao")
                        .HasColumnType("real");

                    b.Property<float>("PercentualMedicao")
                        .HasColumnType("real");

                    b.Property<float>("PercentualProducao")
                        .HasColumnType("real");

                    b.Property<float>("PesoFinal")
                        .HasColumnType("real");

                    b.Property<float>("PesoProduzido")
                        .HasColumnType("real");

                    b.Property<int>("StatusObra")
                        .HasColumnType("integer");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("IdObra");

                    b.HasIndex("IdResponsavelMedicao");

                    b.HasIndex("IdResponsavelProducao");

                    b.HasIndex("IdResponsavelVerificacao");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("API.SIGE.Models.ProducaoFamilia", b =>
                {
                    b.Property<int>("IdProducaoFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducaoFamilia"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataEstimadaConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IdFamiliaCaixilho")
                        .HasColumnType("integer");

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IdProducaoFamilia");

                    b.HasIndex("IdFamiliaCaixilho");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("ProducaoFamilia");
                });

            modelBuilder.Entity("API.SIGE.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("NomeTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("API.SIGE.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Models.UsuarioCargo", b =>
                {
                    b.Property<int>("IdUsuarioCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuarioCargo"));

                    b.Property<int>("IdCargo")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuarioCargo");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdUsuario", "IdCargo")
                        .IsUnique();

                    b.ToTable("UsuarioCargo");
                });

            modelBuilder.Entity("API.SIGE.Models.Anexo", b =>
                {
                    b.HasOne("API.SIGE.Models.Medicao", "Medicao")
                        .WithMany()
                        .HasForeignKey("IdMedicao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Models.ProducaoFamilia", "ProducaoFamilia")
                        .WithMany()
                        .HasForeignKey("IdProducaoFamilia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicao");

                    b.Navigation("ProducaoFamilia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Models.Caixilho", b =>
                {
                    b.HasOne("API.SIGE.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("API.SIGE.Models.FamiliaCaixilho", b =>
                {
                    b.HasOne("API.SIGE.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("API.SIGE.Models.Medicao", b =>
                {
                    b.HasOne("API.SIGE.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("API.SIGE.Models.Notificacao", b =>
                {
                    b.HasOne("API.SIGE.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Models.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("IdUsuarioDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("UsuarioDestino");
                });

            modelBuilder.Entity("API.SIGE.Models.Obra", b =>
                {
                    b.HasOne("API.SIGE.Models.Usuario", "ResponsavelMedicao")
                        .WithMany()
                        .HasForeignKey("IdResponsavelMedicao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Models.Usuario", "ResponsavelProducao")
                        .WithMany()
                        .HasForeignKey("IdResponsavelProducao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Models.Usuario", "ResponsavelVerificacao")
                        .WithMany()
                        .HasForeignKey("IdResponsavelVerificacao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.SIGE.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResponsavelMedicao");

                    b.Navigation("ResponsavelProducao");

                    b.Navigation("ResponsavelVerificacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Models.ProducaoFamilia", b =>
                {
                    b.HasOne("API.SIGE.Models.FamiliaCaixilho", "FamiliaCaixilho")
                        .WithMany()
                        .HasForeignKey("IdFamiliaCaixilho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.SIGE.Models.Usuario", "Responsavel")
                        .WithMany()
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FamiliaCaixilho");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("API.SIGE.Models.Usuario", b =>
                {
                    b.HasOne("API.SIGE.Models.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("API.SIGE.Models.UsuarioCargo", b =>
                {
                    b.HasOne("API.SIGE.Models.Cargo", "Cargo")
                        .WithMany("UsuarioCargos")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.SIGE.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCargos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API.SIGE.Models.Cargo", b =>
                {
                    b.Navigation("UsuarioCargos");
                });

            modelBuilder.Entity("API.SIGE.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioCargos");
                });
#pragma warning restore 612, 618
        }
    }
}
